development:
  url: <%= ENV['DATABASE_URL'] %>

test:
  url: <%= ENV['DATABASE_URL'] %>

prototype:
  url: <%= ENV['DATABASE_URL'] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
