unauthenticated: # layout name
  pages:         # controller name
    - frontpage  # action name
  'devise_registrations':
    - new
    - create
  'devise/sessions':
    - new
    - create
  'devise/passwords':
    - new
    - update
  'devise/confirmations':
    - new
    - create
    - show
