unauthenticated: # layout name
  pages:         # controller name
    - frontpage  # action name
  'devise_registrations':
    - new
    - create
  'devise/sessions':
    - new
    - create
  'devise/passwords':
    - new
    - update
    - create
  'devise/confirmations':
    - new
    - create
    - show
  'devise/unlocks':
    - new
    - create
    - show
  'devise/checkga':
    - show
  tos:
    - index
